### PR TITLE
Always run all commands in all files.

### PR DESCRIPTION
**Pull request by winksaville**
By running all commands in all files we mimic how circleci works and
you know which are passing and which are failing.

So process-matrix will process all files and prints SUCCESS and exits with
0 if all files pass and prints FAILURE and exits with 1 if any file fails.
It invokes circleci-matrix-notemp.sh.

circleci-matrix-all-commands.sh process all commands and exits with 0 if
all succeed and exits with 1 if any fails.

TODO: Update README.md

### CODE REVIEW

**Comment by winksaville** [comment]
Michael,

This change allows circleci-matrix to not stop on errors and instead always run all tests. At the conclusion exits with 0 on success and 1 on failure. I also added process-matrix which will invoke circleci-matrix-all-commands.sh for each of the files passed to it. Thus tests can be broken into many small files if desired.

Finally, I added some tests in tests-wink for now. One unique thing I did was in tests-CIRCLE_NODE_TOTAL_and_INDEX.yml I've included a test that will fail if FAILURE_TEST environment is non-zero, this allow me to verify that the SUCCESS and FAILURE paths. The FAILURE_TEST environment variable can be set in circleci project settings so no code modification needs to be performed.

Anyway, take a look and tell me what you think.

**Comment by michaelcontento** [comment]
Hi and thank you for this contribution! 

I really like the idea of not stopping on the first failed command! But currently I can't merge this PR because of various quality issues. Things that stop me from merging:
- **.gitignore**: Please use a [global gitignore](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore) for files generated by your OS or the default editor you use. I prefer the only put project related stuff in the `.gitignore`, as otherwise every project out there would maintaine (roughly) the same huge `.gitignore` file
- **circle.yml**: [CircleCI](https://github.com/michaelcontento/circleci-matrix/blob/master/circle.yml) is currently used to run the OSX based tests! Linux is tested via [TravisCI](https://github.com/michaelcontento/circleci-matrix/blob/master/.travis.yml). 
- **src/circleci-matrix-all-commands.sh**: Contains 99% the same code as `src/circleci-matrix.sh` and it splits this simple utility over a total of 3 files (`src/circleci-matrix.sh`, `src/circleci-matrix-all-commands.sh` and `process-matrix.sh`). I don't think this is necessary, a good design or adds any benfit at all. It's even worse, as a user is no longer able to use a simple _"wget and run"_ installation method
- **test-wink/***: Please stick to the current bats based testsuite

But I do really like the idea behind this PR! I'm also not afraid to introduce a non BC change and use this _"don't stop on the first error"_-mode as the default one.

A better solution for this feature would be to introduce proper argument handling to `circleci-matrix`. Currently I'm thinking of a API that looks something like:
- `circleci-matrix` (same as `circleci-matrix --config .circleci-matrix.yml`)
- `circleci-matrix --config my-matrix.yml` (same as `circleci-matrix -c my-matrix.yml`)
- `circleci-matrix --stop-on-first-error` (same as `circleci-matrix -s`)

This would follow the common unix approach and we also could introduce `circleci-matrix --help` and `circleci-matrix --version` as a neat little extra :)

**Comment by michaelcontento** [comment]
Please have a look at the [latest master](https://github.com/michaelcontento/circleci-matrix/blob/master/src/circleci-matrix.sh#L40-L70), as I've introduced `--config/-c`, `--help/-h` and `--version` :)

**Comment by michaelcontento** [comment]
I just implemented it myself (see 2b3394ef416f6de8429a435f1f1630d2db38b784). Feel free to comment / add on top of it :)

**Comment by winksaville** [comment]
Your critique was right on the mark and your version is cleaner. I implemented my code in different files because I wanted to be able to test the two side by side, your code and mine. Also, I'm not familiar with bats and had already created this before you made your changes. Anyway, its great thanks!

**Pull request closed without merging**
