### PR TITLE
Run builds using CircleCI 2.0 in an Alpine 3.5 container

### PR DESCRIPTION
**Pull request by devurandom**
Requires aaa798536bb65b240e4cae5eb34275e64e638a66 (#19) and ed9b4fd89cba9fb6dfa870ad5b358cbe129f74d6 (#20) to pass tests, hence the large PR containing a merge.

### CODE REVIEW

**Comment by michaelcontento** [comment]
Please re-base as there are conflicts.

But I very like the idea! With 2ca71d9bb3e70685288db3e8ec28e41c88fe1c1a we would utilize TravisCI for both linux and OSX testing and CircleCI for running circleci-matrix in a docker container. Pretty sweet :-)

The only thing I don't like is the `bats-*` in the `.gitignore`. Is is possible to not require this?

And thank you very much for your effort (in this and all other PRs!).

**Comment by devurandom** [comment]
I added `bats-*` to .gitignore, because that is now being downloaded in the build container. When I run `circleci build` locally, I will thus be left with the tarball and bats directory in my project folder, which seemed distracting.

**Comment by devurandom** [comment]
83d2b87b8a321d21dc8328f0514a48ea8c39f932 fails, while 3378803ee64e82245a207ecaf6d9e37339b19a59 succeeds, because the former is still using the old CircleCI v1 config and tries to build on OSX with `brew`, which is missing there.

**Comment by devurandom** [comment]
The major benefit of using CircleCI containers is, IMO, that test can happen in a completely different environment, musl libc without coreutils, for example, which might help catch unusual problems.

**Comment by michaelcontento** [comment]
Thanks a lot! 👍

**Pull request merged**
